### ISSUE TITLE
stata 贝叶斯

### ISSUE THREAD

**Issue by dm20001009** [worldbank/stata#48] opened 2023-03-25 03:27 UTC

**Comment by kbjarkefur** [comment] 2023-03-25 14:23
贝叶斯 = bayesian, right? We need more info to keep this issue open.

**Comment by luizaandrade** [comment] 2023-03-25 20:10
Well, I don't understand it, so it probably is bayesian.

**Comment by kbjarkefur** [comment] 2023-03-30 07:33
Closed as it is not clear what the issue is. :)

**Closed** 2023-03-30 07:32 UTC
